### ISSUE TITLE
Rugby Pass error

### ISSUE THREAD

**Issue by hidemyassbaby** [matthuisman/plugin.video.rugbypass#2]
Hi

Found a issue on rugby pass I try to play a live match or past game and it errors here is issues I am getting

Lastest kodi 18.2 android
![Screenshot_20190518_204015_org xbmc kodi](https://user-images.githubusercontent.com/49113438/57966995-627a5c00-79ad-11e9-9ff2-c38727ec4e8f.jpg)
![Screenshot_20190518_183853_org xbmc kodi](https://user-images.githubusercontent.com/49113438/57966999-6b6b2d80-79ad-11e9-860c-3f7700945ec9.jpg)

**Comment by hidemyassbaby** [comment]
Account issue works

**Comment by matthuisman** [comment]
Still a Error with the error that I need to fix though :)

**Comment by matthuisman** [comment]
Just pushed 0.21.4 which will give you the correct "nice" error.
Which basically says, error getting that item to play - check your subscription.
